// Package handler — deploy.go
// Auto deploy เว็บใหม่: สร้าง nginx config + reload
//
// เมื่อสร้าง agent_node พร้อม domain:
//  1. เขียนไฟล์ nginx server block → /etc/nginx/sites-enabled/{domain}.conf
//  2. nginx -t (test config)
//  3. nginx -s reload
//  4. เว็บพร้อมใช้งาน — รอแค่ชี้ DNS
//
// Architecture:
//
//	nginx (reverse proxy) รับทุก domain
//	→ proxy_pass ไป member-web 1 instance (port 3001)
//	→ member-web ส่ง request ไป member-api
//	→ member-api detect domain จาก X-Forwarded-Host → scope ข้อมูลตาม agent_node_id
package handler

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/farritpcz/lotto-standalone-admin-api/internal/cloudflare"
)

// DeployConfig เก็บ config สำหรับ deploy
type DeployConfig struct {
	NginxSitesDir string // เช่น /etc/nginx/sites-enabled
	MemberWebPort string // เช่น 3001
	ServerIP      string // IP สำหรับบอก user ชี้ DNS
}

// DeployResult ผลลัพธ์การ deploy
type DeployResult struct {
	Success     bool     `json:"success"`
	Message     string   `json:"message"`
	ServerIP    string   `json:"server_ip,omitempty"`   // IP สำหรับชี้ DNS (เดิม, ใช้เมื่อไม่มี CF)
	FilePath    string   `json:"file_path,omitempty"`   // path ของ nginx config ที่สร้าง
	Nameservers []string `json:"nameservers,omitempty"` // ⭐ Cloudflare nameservers (ใหม่)
	CFZoneID    string   `json:"cf_zone_id,omitempty"`  // ⭐ Cloudflare Zone ID (เก็บ DB)
}

// nginxTemplate สร้าง nginx server block สำหรับ domain
// ⭐ ใช้ X-Forwarded-Host เพื่อให้ member-api detect domain ได้ถูกต้อง
func nginxTemplate(domain string, memberWebPort string) string {
	return fmt.Sprintf(`# Auto-generated by lotto-admin-api — domain: %s
# ห้ามแก้ไข manual — จะถูก overwrite เมื่อ deploy ใหม่

server {
    listen 80;
    server_name %s;

    # ⭐ Proxy ไป member-web instance เดียว
    location / {
        proxy_pass http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeout สำหรับ WebSocket (ยี่กี real-time)
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Static assets cache
    location /_next/static/ {
        proxy_pass http://127.0.0.1:%s;
        proxy_cache_valid 200 365d;
        add_header Cache-Control "public, immutable";
    }
}
`, domain, domain, memberWebPort, memberWebPort)
}

// validDomain เช็คว่า domain ถูกรูปแบบ
var validDomainRegex = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*\.[a-zA-Z]{2,}$`)

func validDomain(domain string) bool {
	return validDomainRegex.MatchString(domain) && len(domain) <= 200
}

// DeployNginxConfig สร้าง nginx config สำหรับ domain ใหม่ + reload nginx
//
// ขั้นตอน:
//  1. Validate domain format
//  2. สร้างไฟล์ /etc/nginx/sites-enabled/{domain}.conf
//  3. nginx -t (test config syntax)
//  4. nginx -s reload (apply config)
//
// ถ้า nginx -t fail → ลบไฟล์ที่สร้าง + return error
func DeployNginxConfig(cfg DeployConfig, domain string) DeployResult {
	// Validate
	domain = strings.TrimSpace(strings.ToLower(domain))
	if !validDomain(domain) {
		return DeployResult{Success: false, Message: "รูปแบบ domain ไม่ถูกต้อง"}
	}

	// สร้าง nginx config content
	content := nginxTemplate(domain, cfg.MemberWebPort)

	// เขียนไฟล์
	filename := filepath.Join(cfg.NginxSitesDir, domain+".conf")
	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		log.Printf("❌ Deploy: เขียน nginx config ไม่สำเร็จ %s: %v", filename, err)
		return DeployResult{
			Success: false,
			Message: fmt.Sprintf("เขียน nginx config ไม่สำเร็จ: %v (ตรวจสอบ NGINX_SITES_DIR=%s)", err, cfg.NginxSitesDir),
		}
	}
	log.Printf("📝 Deploy: สร้าง nginx config → %s", filename)

	// Test nginx config
	testCmd := exec.Command("nginx", "-t")
	if output, err := testCmd.CombinedOutput(); err != nil {
		// Config ผิด → ลบไฟล์ที่สร้าง
		os.Remove(filename)
		log.Printf("❌ Deploy: nginx -t failed: %s", string(output))
		return DeployResult{
			Success: false,
			Message: fmt.Sprintf("nginx config ไม่ถูกต้อง — rollback แล้ว: %s", string(output)),
		}
	}

	// Reload nginx
	reloadCmd := exec.Command("nginx", "-s", "reload")
	if output, err := reloadCmd.CombinedOutput(); err != nil {
		log.Printf("⚠️ Deploy: nginx reload failed: %s", string(output))
		return DeployResult{
			Success:  true, // config ถูกสร้างแล้ว แค่ reload ไม่สำเร็จ
			Message:  fmt.Sprintf("สร้าง config สำเร็จ แต่ reload nginx ไม่ได้: %s — กรุณา reload manual", string(output)),
			ServerIP: cfg.ServerIP,
			FilePath: filename,
		}
	}

	log.Printf("✅ Deploy: nginx reload สำเร็จ — %s พร้อมใช้งาน", domain)
	return DeployResult{
		Success:  true,
		Message:  fmt.Sprintf("เว็บ %s พร้อมใช้งาน — กรุณาชี้ DNS A record มาที่ %s", domain, cfg.ServerIP),
		ServerIP: cfg.ServerIP,
		FilePath: filename,
	}
}

// RemoveNginxConfig ลบ nginx config ของ domain (ใช้ตอนลบเว็บ/ปิดเว็บ)
func RemoveNginxConfig(cfg DeployConfig, domain string) error {
	filename := filepath.Join(cfg.NginxSitesDir, domain+".conf")
	if err := os.Remove(filename); err != nil && !os.IsNotExist(err) {
		return err
	}
	// Reload nginx
	exec.Command("nginx", "-s", "reload").Run()
	log.Printf("🗑️ Deploy: ลบ nginx config %s + reload", filename)
	return nil
}

// =============================================================================
// Cloudflare Zone Deploy — สร้าง zone + DNS record อัตโนมัติ
// =============================================================================

// DeployCloudflareZone สร้าง Cloudflare zone สำหรับ domain ลูกค้า
//
// Flow:
//  1. สร้าง zone ใน CF (หรือดึง zone เดิมถ้ามีอยู่แล้ว)
//  2. เพิ่ม A record ชี้ไป server IP (proxied = ซ่อน IP ☁️)
//  3. เพิ่ม A record สำหรับ www subdomain
//  4. ตั้ง SSL mode = flexible (ไม่ต้อง cert บน server)
//  5. Return nameservers ให้ frontend แสดงบอกลูกค้า
//
// Parameters:
//   - cfClient: Cloudflare API client (ต้องไม่เป็น nil)
//   - domain: ชื่อ domain เช่น "huay99.com"
//   - serverIP: IP ของ server จริง (จะถูกซ่อนหลัง CF proxy)
func DeployCloudflareZone(cfClient *cloudflare.Client, domain, serverIP string) DeployResult {
	// ── 1. สร้าง Zone ──
	zone, err := cfClient.CreateZone(domain)
	if err != nil {
		log.Printf("❌ CF Deploy: สร้าง zone %s ไม่สำเร็จ: %v", domain, err)
		return DeployResult{
			Success: false,
			Message: fmt.Sprintf("สร้าง Cloudflare zone ไม่สำเร็จ: %v", err),
		}
	}

	// ── 2. เพิ่ม A record (root domain) — proxied ☁️ ──
	if err := cfClient.AddDNSRecord(zone.ZoneID, "A", domain, serverIP, true); err != nil {
		log.Printf("⚠️ CF Deploy: เพิ่ม A record %s ไม่สำเร็จ: %v", domain, err)
		// ไม่ return error — zone สร้างสำเร็จแล้ว แค่ DNS ยังไม่ได้เพิ่ม
	}

	// ── 3. เพิ่ม A record (www subdomain) — proxied ☁️ ──
	if err := cfClient.AddDNSRecord(zone.ZoneID, "A", "www."+domain, serverIP, true); err != nil {
		log.Printf("⚠️ CF Deploy: เพิ่ม www A record ไม่สำเร็จ: %v", err)
	}

	// ── 4. ตั้ง SSL mode = flexible ──
	// flexible = CF จัดการ HTTPS ให้, ไม่ต้อง cert บน origin server
	if err := cfClient.SetSSLMode(zone.ZoneID, "flexible"); err != nil {
		log.Printf("⚠️ CF Deploy: ตั้ง SSL mode ไม่สำเร็จ: %v", err)
	}

	log.Printf("✅ CF Deploy: %s สำเร็จ — NS: %v (zone: %s)", domain, zone.NameServers, zone.ZoneID)

	return DeployResult{
		Success:     true,
		Message:     fmt.Sprintf("สร้างเว็บ %s สำเร็จ — กรุณาเปลี่ยน Nameserver ของโดเมน", domain),
		Nameservers: zone.NameServers,
		CFZoneID:    zone.ZoneID,
	}
}
